apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
  namespace: streamingapp
data:
  NODE_ENV: "production"
  APP_ENV: "production"

  # MongoDB
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "streamingapp"

  # Internal Kubernetes service URLs
  AUTH_SERVICE_URL: "http://auth:3001"
  STREAMING_SERVICE_URL: "http://streaming:3002"
  ADMIN_SERVICE_URL: "http://admin:3003"
  CHAT_SERVICE_URL: "http://chat:3004"

  # Frontend
  API_BASE_URL: "/api"

