apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secret
  namespace: streamingapp
type: Opaque
stringData:
  MONGO_USERNAME: "streamingapp"
  MONGO_PASSWORD: "streamingapp123"

  JWT_SECRET: "gWzgvK1ImRGinUPscFdRUjnWCl+H/WdKk9dfjhZxau8="

  # If your application requires these:
  AUTH_SECRET: "auth-secret-change-me"
  SESSION_SECRET: "session-secret-change-me"
  